title: "À l'écoute du territoire"
description: "À l'écoute du territoire est une émission, réalisée par Renaud Chicoine-McKenzie et Paul Fontaine, de longs reportages sur les voix, les vies et les défis du territoire québécois."
baseurl: ""
url: "http://www.ecouterleterritoire.com"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Podcast Feed settings
title:          "À l'écoute du territoire"
email:          ecouter.le.territoire@gmail.com
description:    "À l'écoute du territoire est une émission, réalisée par Renaud Chicoine-McKenzie et Paul Fontaine, de longs reportages sur les voix, les vies et les défis du territoire québécois."
subtitle:       "A podcast about saving your podcast."
url:            http://www.ecouterleterritoire.com/
language:       fr-ca
author:         Renaud Chicoine-McKenzie et Paul Fontaine
copyright:      "CC BY 4.0"

feed:
  collections:
    episodes:
      path: "/episodes.xml"

collections:
  episodes:
